<?php
/*
 Minimal vulnerable harness for MerlinWP wp_ajax_merlin_child_theme CSRF/AuthZ.
 Affected source pattern from class-merlin.php:
   add_action('wp_ajax_merlin_child_theme', [$this, 'generate_child']);
   public function generate_child() { ... mkdir child theme; put style.css;
       put functions.php; update_option('allowedthemes', ...); switch_theme($slug); }
 generate_child() does not call check_ajax_referer('merlin_nonce','wpnonce')
 and does not call current_user_can(...).
*/
$themeRoot = __DIR__ . '/themes';
$optionsFile = __DIR__ . '/options.json';
@mkdir($themeRoot, 0777, true);
if (!file_exists($optionsFile)) {
    file_put_contents($optionsFile, json_encode(['allowedthemes' => [], 'active_theme' => 'demo-theme'], JSON_PRETTY_PRINT));
}
function generate_child_theme($themeRoot, $optionsFile) {
    $parentTemplate = 'demo-theme';
    $parentName = 'Demo Theme';
    $childName = $parentName . ' Child';
    $slug = 'demo-theme-child';
    $path = $themeRoot . '/' . $slug;
    if (!file_exists($path)) {
        mkdir($path, 0777, true);
        file_put_contents($path . '/style.css', "/*\nTheme Name: $childName\nTemplate: $parentTemplate\n*/\n");
        file_put_contents($path . '/functions.php', "<?php\n// child theme bootstrap generated by vulnerable AJAX action\n");
    }
    $options = json_decode(file_get_contents($optionsFile), true) ?: [];
    $options['allowedthemes'][$slug] = true;
    $options['merlin_demotheme_child'] = $childName;
    $options['active_theme'] = $slug;
    $options['received_wpnonce'] = array_key_exists('wpnonce', $_POST);
    $options['received_capability_marker'] = array_key_exists('can_manage_options', $_POST);
    file_put_contents($optionsFile, json_encode($options, JSON_PRETTY_PRINT));
    header('Content-Type: application/json');
    echo json_encode(['done' => 1, 'message' => "Child theme $slug generated and activated"]);
}

$method = $_SERVER['REQUEST_METHOD'];
$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
if ($path === '/wp-admin/admin-ajax.php' && $method === 'POST' && ($_POST['action'] ?? '') === 'merlin_child_theme') {
    // Simulate wp_ajax_*: only checks logged-in state. The vulnerable function
    // performs no nonce or capability check after this point.
    if (empty($_COOKIE['wordpress_logged_in'])) {
        http_response_code(401);
        echo json_encode(['error' => 'login required']);
        return;
    }
    generate_child_theme($themeRoot, $optionsFile);
    return;
}
if ($path === '/state' && $method === 'GET') {
    header('Content-Type: application/json');
    echo json_encode([
        'options' => json_decode(file_get_contents($optionsFile), true),
        'child_style_exists' => file_exists($themeRoot . '/demo-theme-child/style.css'),
        'child_functions_exists' => file_exists($themeRoot . '/demo-theme-child/functions.php'),
    ], JSON_PRETTY_PRINT);
    return;
}
http_response_code(404);
echo "Not found\n";
